stages:
  - docker
  - test
  
docker:
  only:
    - schedules
  image: docker:latest
  services:
    - docker:dind
  stage: docker
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - cd ci/docker/rust
    - docker build --no-cache -t registry.gitlab.com/dzamlo/gitlab-ci-rust-test/rust:latest .
    - docker push registry.gitlab.com/dzamlo/gitlab-ci-rust-test/rust:latest

.rust_test_template: &rust_test_template
  stage: test
  image: "registry.gitlab.com/dzamlo/gitlab-ci-rust-test/rust:latest"
  cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - cargo/
      - target/
  before_script:
    - export CARGO_HOME="$CI_PROJECT_DIR/cargo"
    - rustup --version
    - rustc --version
    - cargo --version
  script:
    - cargo build
    - cargo test --all -- --test-threads=1

test-stable:
  <<: *rust_test_template
  variables:
    RUSTUP_TOOLCHAIN: stable
    
test-beta:
  <<: *rust_test_template
  variables:
    RUSTUP_TOOLCHAIN: beta

test-nightly:
  <<: *rust_test_template
  variables:
    RUSTUP_TOOLCHAIN: nightly
    
test-minimal-versions:
  <<: *rust_test_template
  variables:
    RUSTUP_TOOLCHAIN: nightly
  script:
    - cargo test --all -Z minimal-versions -- --test-threads=1
    
test-fmt:
  <<: *rust_test_template
  variables:
    RUSTUP_TOOLCHAIN: nightly
  script:
    - cargo fmt --all -- --check
    
test-clippy:
  <<: *rust_test_template
  variables:
    RUSTUP_TOOLCHAIN: stable
  script:
    - rustup component add clippy
    - cargo clippy --all -- -D warnings
    
test-prerelase:
  stage: test
  image: "buildpack-deps:stretch"
  when: manual 
  variables:
    RUSTUP_DIST_SERVER: https://dev-static.rust-lang.org
    CARGO_HOME: "$CI_PROJECT_DIR/cargo"
  before_script:
    - export PATH="$CARGO_HOME/bin:$PATH"
    - curl https://sh.rustup.rs -sSf | sh -s -- -y  --default-toolchain stable
    - rustup component add rustfmt-preview
    - rustup --version
    - rustc --version
    - cargo --version
  script:
      - cargo test --all -- --test-threads=1
      - cargo fmt --all -- --write-mode=diff